version: "3.9"

services:
#  azureTextToSpeechNeural:
#    image: mcr.microsoft.com/azure-cognitive-services/speechservices/neural-text-to-speech
#    container_name: azureTextToSpeechNeural
#    ports:
#      - "10000:10000"

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: azurite
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"
    volumes:
      - azurite:/home/shaggy/docker/azurite

  postgres:
    image: ionx/postgres-plv8:12.2
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: Password12!
      POSTGRES_USER: postgres

  rabbitmq:
    image: masstransit/rabbitmq
    container_name: rabbit-mq
    ports:
      - "15672:15672"
      - "5672:5672"
        
  mail:
    image: bytemark/smtp
    container_name: mail
    restart: always
    ports:
      - "25:25"
    environment:
      RELAY_HOST: smtp-relay.sendinblue.com
      RELAY_PORT: 587
      RELAY_USERNAME: lukasz.mojek@gmail.com
      RELAY_PASSWORD: 0ypCIQATcnENd8Vs

volumes:
  azurite:

  postgres:
    driver: local